### ISSUE TITLE
Not able to run on university cluster/google colab.

### ISSUE THREAD

**Issue by Amangoel32** [PingYu-iris/SA-GCN#1]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/47176352/88370878-9078de80-cdb0-11ea-893f-aa31a111ec22.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/47176352/88370882-91aa0b80-cdb0-11ea-911f-e4c15bf341be.png)

Getting the same error on both the environment. Would you be able to provide us with the library dependencies that you were running at the time of execution?

**Comment by PingYu-iris** [comment]
Hi there,

I used python 3.6.9 with pytorch 1.4.0.

I think the problem is caused by 

```
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="3"
```
in train.py.  These two lines choose the fourth gpu but you don't have that. I have already uncommented those two lines. Please make a try.

**Comment by Amangoel32** [comment]
Hey sorry for the late response, I had somehow forgotten which github account I had used to post. Thanks for the prompt response. That had resolved the issue.
