### ISSUE TITLE
Are root positions considered while generation?

### ISSUE THREAD

**Issue by EricGuo5513** [PingYu-iris/SA-GCN#3]
Hi, thanks for your interesting work. I want to compare with your method but I have one quick question. Are root positions considered when you generate these motions? Or the root is pinned at the origin constantly. Because the shown results in your work seems there is no global dispalcement. It's kind of important to me.

best

**Comment by PingYu-iris** [comment]
Hi Eric,

I am really glad that you want to compare your model with my model. During our generation, we didn't consider the root positions.

Hope my answer will help you.

Best,
Ping
