### ISSUE TITLE
Question about MMD 

### ISSUE THREAD

**Issue by dhk1349** [PingYu-iris/SA-GCN#6]
In the util/evaluation.py calculate_mmd function, there are two modes (avg and joint).
Does joint score means MMD seq score?? If not,  how can I get MMD seq score?

Thanks for your code :)

**Comment by PingYu-iris** [comment]
we denote MMD_{avg} as the average MMD over each frame and MMD_{seq} to denote the
MMD over whole sequences in the paper.

In this code, the avg means MMD_{avg} and joint means MMD_{seq}.

**Comment by dhk1349** [comment]
Thanks for your reply!
