### ISSUE TITLE
NTU RGB+D Missing Link

### ISSUE THREAD

**Issue by DegardinBruno** [PingYu-iris/SA-GCN#7]
Hello Ms. Yu,

Thank you for your excellent work!
Just one small question, your current drive link "Can not be found".
Could you please provide a new link or way to reach your files?

Thank you once again for your attention.

**Comment by PingYu-iris** [comment]
Hi sorry for the delay. I uploaded the data again. [https://drive.google.com/file/d/1jppqKE1WOaD-4jWD9pInV9aXKbqrJZOF/view?usp=sharing]

**Comment by DegardinBruno** [comment]
Really appreciate it!
Thank you for that!
